### ISSUE TITLE
Camera Intent Exceptions

### ISSUE THREAD

**Issue by vdidxho** [xamarin/docs-archive#76]
The Camera Intent recipe in recipes/Recipes/android/other_ux/camera_intent/take_a_picture_and_save_using_camera_app/ experiences some exceptions. When run with SDK 23 it throws an exception due to permissions having not been requested first. More importantly when run on SDK 28 it throws Android.OS.FileUriExposedException. Please update when possible.

**Comment by codrut-n** [comment]
In Android N+ there are no more file:// URIs, only content:// URIs instead. That's why Camera Activity can't work with Uri.FromFile(App._file).
The solution, changed for VS Xamarin, I used:

protected override void OnCreate(Bundle savedInstanceState){
  StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
  StrictMode.SetVmPolicy(builder.Build());
  base.OnCreate(savedInstanceState);
  ...
}
Other code is without changes.

I tried it on Android N 7.1.1 on real device and it's works.
